version: 2

builds:
  # Linux build (needs CGO for ALSA)
  - id: linux
    main: .
    binary: waves
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  # macOS build (pure Go via purego)
  - id: darwin
    main: .
    binary: waves
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  # Windows build (pure Go via purego)
  - id: windows
    main: .
    binary: waves
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  # Release notes are passed via --release-notes flag in the workflow
