name: Nix Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - name: Build with Nix
        run: nix build .#
